# Artificial Neural Network

### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

In [5]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

### Importing the dataset

In [6]:
print(x)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [7]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Encoding categorical data

In [ ]:
# No encoding required as the dataset hai only numerical values

### Splitting the dataset into the Training set and Test set

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [10]:
print(x_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [11]:
print(y_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


In [12]:
print(x_test)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


In [13]:
print(y_test)

[431.23 460.01 461.14 ... 473.26 438.   463.28]


### Feature Scaling

In [ ]:
# Not requires as all are numeric data and can be used

## Part 2 - Building the ANN

### Initializing the ANN

In [14]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [17]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [18]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')
#As we are not dealing with binary value hence

### Training the ANN on the Training set

In [20]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 2ms/step - loss: 205774.6094
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 205774.7344
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 205774.6719
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 205774.6875
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 205774.6406
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 205774.7031
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 205774.6875
Epoch 8/100
240/240 [==============================] - 0s 2ms/step - loss: 205774.6875
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 205774.7344
Epoch 10/100
240/240 [==============================] - 0s 2ms/step - loss: 205774.5781
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 205774.7188
Epoch 12/100
240/240 [===================

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [26]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 1ms/step
[[  1.   431.23]
 [  1.   460.01]
 [  1.   461.14]
 ...
 [  1.   473.26]
 [  1.   438.  ]
 [  1.   463.28]]


### Making the Confusion Matrix