In [1]:
import numpy as np

In [2]:
a = np.array([1, 2 , 3])

In [4]:
 print(a)
    
    

[1 2 3]


In [8]:
 a1 = np.array([[1, 2 , 3],[4,5,6]])
print(a1)

#its a 2d array

[[1 2 3]
 [4 5 6]]


In [12]:
 #to get a specific element 
a1[1,2]

6

In [13]:
# to get a specific row 
a1[0,:]

array([1, 2, 3])

In [15]:
# to get a specific column 
print (a1[:,2])

[3 6]


In [17]:
# changing the element 
a1[1,2] = 20
print(a1)

[[ 1  2  3]
 [ 4  5 20]]


In [18]:
# INITIALIZING DIFFERENT TYPES OF ARRAYS 

In [20]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [29]:
import numpy as np

arr = np.array([1, 2, 3, 7, 5, 6, 8])

# slicing the array before 4 th index
#print(arr[4:])

#Slice from the index 3 from the end to index 1 from the end:

print(arr[-3:-1])


[5 6]


In [30]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])


[7 8 9]


In [70]:
#this gives the datatype of an array
print(arr.dtype)
# to give a data type use 
dtype = np.float32

<attribute 'dtype' of 'numpy.generic' objects>


In [69]:
# this gives the dimensions of the array 
print(arr.ndim)

1


In [37]:
# WHAT IS A  VIEW AND WHAT IS A COPY OF AN ARRAY
arr = np.array([3,4,5,6])
x = arr.copy()
arr[0]=20
print(arr)
print(x)

# in copy the orignal array dosen't change 

[20  4  5  6]
[3 4 5 6]


In [36]:
# WHAT IS A  VIEW AND WHAT IS A COPY OF AN ARRAY
arr = np.array([3,4,5,6])
x = arr.view()
arr[0]=20
print(arr)
print(x)

[20  4  5  6]
[20  4  5  6]


In [38]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)


None
[1 2 3 4 5]


In [42]:
# how to reshape or change dimensions of an arrayimport numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
# Convert the following 1-D array with 12 elements into a 3-D array.

# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
#2d, rows, columns
newarr = arr.reshape(2, 3, 2)

print(newarr)

#this converts the 1 d array into a 3d array

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [48]:
# flattening the array means changing the array into a a 1D array
# we can use reshape(-1) 
import numpy as np
arr = np.array([[1, 2, 3, 4, 5],[ 6, 7, 8, 10, 11, 12]])
newarr = arr.reshape(-1)
print(newarr)

[list([1, 2, 3, 4, 5]) list([6, 7, 8, 10, 11, 12])]


/var/folders/d5/zstxby4j7mxfxsrnpgf5wfy00000gn/T/ipykernel_5494/762928618.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[1, 2, 3, 4, 5],[ 6, 7, 8, 10, 11, 12]])


In [52]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
for x in arr:
    print (x)

1
2
3
4
5
6
7
8
9
10
11
12


In [56]:
# INTERATION IN A 2D ARRAY LOOK FOR CORRECT INDENTATION
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [57]:
# TO SEARCH A VALUE IN A ARRAY

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)
# RETURNS THE INDEX WHERE ARRAY IS PRESENT 

(array([3, 5, 6]),)


In [58]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [63]:
# SEARCH SORTED FUNCTION USE 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.searchsorted(arr,7)
print(x)
# this gives index for number 7 and puts it in place 1 
print(arr)

6
[1 2 3 4 5 6 7 8]


In [66]:
# SEARCH SORTED FUNCTION USE wrt side
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.searchsorted(arr,7,side='right')
print(x)

7


In [67]:
# sorting of an array using numpy

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

#sorted array is printed 

[0 1 2 3]


In [75]:
# To use filters to and array that means 
# we can use if else statement

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, False, True, True]
[43 44]
